### ISSUE TITLE
Publish snapshots to IPFS

### ISSUE THREAD

**Issue by placer14** [travisperson/filsnap#17]
As a stretch goal and an idealism, let's publish these to IPFS and pin to a cluster specifically for these snapshots. This will allow us to dogfood our software and allow others to easily share the burden of sharing these (by just joining the IPFS cluster). (This implies that the info needed to join the new cluster is published as well.)

**Comment by travisperson** [comment]
This repo does not cover any deployment of this software. A better place for this would be in [filecoin-project/lotus-infra](https://github.com/filecoin-project/lotus-infra).

If you want support for [pinning services api](https://ipfs.github.io/pinning-services-api-spec/) that can be opened as a feature request.

**Comment by placer14** [comment]
NP. Opened https://github.com/filecoin-project/lotus-infra/issues/682.
